// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  documentationSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        'intro/intro',
        'intro/why',
        'intro/how',
        'intro/use',
        'intro/next',

        // {
        //   type: 'category',
        //   label: 'Introduction',
        //   items: ['why', 'how'],
        // },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'getting-started/signup',
        'getting-started/generate',
        'getting-started/first-request',

        // {
        //   type: 'category',
        //   label: 'Introduction',
        //   items: ['why', 'how'],
        // },
      ],
    },
    {
      type: 'category',
      label: 'Voice Cloning',
      collapsible: true,
      collapsed: false,
      items: [
        'voice-cloning/instant',
        'voice-cloning/custom'

        // {
        //   type: 'category',
        //   label: 'Introduction',
        //   items: ['why', 'how'],
        // },
      ],
    },
    {
      type: 'doc',
      id: 'voice-library', // document ID
    },
    {
      type: 'doc',
      id: 'models', // document ID
    },
    {
      type:'doc',
      id: 'pricing',
    },
    {
      type: 'doc',
      id: 'authentication', // document ID
    },
    {
      type: 'doc',
      id: 'endpoints', // document ID
    },

  ],
};

export default sidebars;
