// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api-intro', // document ID
      label: 'Introduction', // sidebar label
    },
    {
      type: 'doc',
      id: 'authentication', // document ID
      label: 'Authentication', // sidebar label
    },
    {
      type: 'category',
      label: 'Endpoints',
      collapsible: true,
      collapsed: false,
      items: [
        'endpoints/tts',
        'endpoints/status',
        'endpoints/voices'
      ],
    },
    {
      type:'doc',
      id:'credits'
    },
    {
      type:'doc',
      id:'errors'
    }
  ]
};

export default sidebars;
